# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab',
            name='aciklama',
        ),
        migrations.AddField(
            model_name='lab',
            name='capacity',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lab',
            name='explanation',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
