# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 16:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('office_code', models.CharField(max_length=20)),
                ('e_mail', models.EmailField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('web_site', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
