# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecturer', '0003_lecturer_bolum'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
    ]
