# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecturer', '0004_lecturer_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
