# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=10)),
                ('term', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], default='Fall', max_length=10)),
            ],
        ),
    ]
