# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
