# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecturer', '0001_initial'),
        ('app_lecture', '0002_lecture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecturer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app_lecturer.Lecturer'),
            preserve_default=False,
        ),
    ]
