# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecture', '0006_lecture_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='kredi',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
