# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecture', '0007_lecture_kredi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='kredi',
            field=models.CharField(blank=True, default='0', max_length=3, null=True),
        ),
    ]
