# Generated by Django 2.0 on 2017-12-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecture', '0009_lecture_secme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('question', models.TextField(blank=True)),
                ('mail', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
