# Generated by Django 2.0 on 2017-12-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_lecture', '0010_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
