# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_lab', '0002_auto_20171227_1255'),
        ('app_lecture', '0012_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_lab.Lab'),
        ),
    ]
