# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-23 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_auto_20171224_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
